### ISSUE TITLE
Could we get an online version hosted on GitHub pages?

### ISSUE THREAD

**Issue by Bilge** [tigt/mini-svg-data-uri#1]
This would be very convenient whether or not people are comfortable using Node.

**Comment by tigt** [comment]
I’d like to do this, but I’m scatterbrained and have other stuff pulling on my time, so I can’t promise it'll happen.

There are two similar tools on CodePen that let you paste in an SVG and get a similarly-encoded URI, if that works for you:

* [Encode SVG SCSS by jakob-e (includes Sass `@function`)](https://codepen.io/jakob-e/pen/doMoML)
* [SVG encoded for `background-image` by shshaw](https://codepen.io/shshaw/full/rrOZQQ)

They don’t do everything this does, but they’re very close.

**Comment by Bilge** [comment]
Nice label and sorry to hear about your brain! Thanks doubly for the links!

**Comment by tigt** [comment]
Oh, RunKit + npm also have [an in-browser version of this specifically](https://npm.runkit.com/mini-svg-data-uri).

Here’s a [RunKit snippet that should do what you want](https://runkit.com/embed/o0641isnb3ce) if you replace `your SVG goes here` with, well, your SVG.

**Comment by tigt** [comment]
I went ahead and put the RunKit snippet in the repo site field, so it’s easily findable. It’s about as good as any in-browser version I could create, anyway.

Thanks for opening this!

**Comment by Bilge** [comment]
I think you put the wrong one in there. The first link is usable and includes documentation but the second requires sign-up and has no documentation. You might also consider putting it directly in the readme.

**Comment by tigt** [comment]
Weird, I can’t seem to get the sign-up version even with a different browser’s private browsing. Good catch, updated.

EDIT: Put it in the “Usage” section of the README too.
