### ISSUE TITLE
Incorrect function name referenced in example?

### ISSUE THREAD

**Issue by jonnystening** [tigt/mini-svg-data-uri#12]
`svgToMiniDataURI()` in README.md example vs `svgToTinyDataUri()` exported in code

**Comment by tigt** [comment]
Oh, good catch. It’s the default export so the name doesn’t matter as far as I know. Is it giving you problems?

**Comment by jonnystening** [comment]
It’s all good. Just mentioning it for consistency. Is it tiny or mini? Big decisions 🤣

**Comment by tigt** [comment]
As you might have sussed out, I waffled between the two before publishing.

Now I realize this will drop in popularity as soon as somebody grabs the <code><b><i>nano</i></b>-svg-data-uri</code> package name.
