### ISSUE TITLE
Why single quotes?

### ISSUE THREAD

**Issue by shellscape** [tigt/mini-svg-data-uri#13]
I was hoping to see the "why" documented in the readme - Why are double quotes replaced by single quotes? It's causing some headache in our implementation and I'd like to be able to speak on why that choice was made.

**Comment by sylvaindumont** [comment]
https://codepen.io/tigt/post/optimizing-svgs-in-data-uris#its-all-in-the-quotes-1

**Comment by shellscape** [comment]
![thanks!](https://i.imgur.com/BrUW1rG.jpg)

**Comment by Yaffle** [comment]
IE 11 does not support unencoded double quotes.
It is possible to use single quotes for CSS strings, so you may use double quotes.
