### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by madamadami** [tigt/mini-svg-data-uri#14]
Thanks for your article and your code. I tried it here https://runkit.com/embed/b3g4cq89e8ys but I get a **ReferenceError: svgToMiniDataURI** is not defined. I looked in your code and saw the function is named **svgToTinyDataUri**, but with line `var optimizedSVGDataURI = svgToTinyDataUri(svg);` I get a not defined error as well. Would be glad, if you could explain me what's wrong with my code.

**Comment by tigt** [comment]
To fix your problem, you would change the code to look more like this:

```js
var miniSvgDataUri = require("mini-svg-data-uri");
var svg = '<svg version="1.1" id="level1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" viewBox="0 0 16 20" xml:space="preserve"><style>.st0{fill:#020203}.st1{fill:#010202}</style><path class="st0" d="M16 4v15c0 .6-.4 1-1 1H1c-.6 0-1-.4-1-1V4c0-.6.4-1 1-1h2v1H1v15h14V4h-2V3h2c.6 0 1 .4 1 1z"/><path class="st0" d="M10 2c0-1.1-.9-2-2-2S6 .9 6 2H4v3h8V2h-2zM3.7 7H14v1H3.7z"/><circle class="st1" cx="2.6" cy="7.5" r=".6"/><path class="st0" d="M3.7 16H14v1H3.7z"/><circle class="st1" cx="2.6" cy="16.5" r=".6"/><g><path class="st0" d="M3.7 10H14v1H3.7z"/><circle class="st1" cx="2.6" cy="10.5" r=".6"/></g><g><path class="st0" d="M3.7 13H14v1H3.7z"/><circle class="st1" cx="2.6" cy="13.5" r=".6"/></g></svg>';
var optimizedSVGDataURI = miniSvgDataUri(svg);
```

You’re not the only person to be confused by the different function names (see #12), so clearly I should update the readme.

By the way, your SVG could be optimized even better by running it repeatedly through [SVGOMG](https://jakearchibald.github.io/svgomg/) first. That would make your input to this tool look like:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 20"><path d="M16 4v15c0 .6-.4 1-1 1H1c-.6 0-1-.4-1-1V4c0-.6.4-1 1-1h2v1H1v15h14V4h-2V3h2c.6 0 1 .4 1 1z" class="st0"/><path d="M10 2c0-1.1-.9-2-2-2S6 .9 6 2H4v3h8V2h-2zM3.7 7H14v1H3.7z" class="st0"/><circle cx="2.6" cy="7.5" r=".6" class="st1"/><path d="M3.7 16H14v1H3.7z" class="st0"/><circle cx="2.6" cy="16.5" r=".6" class="st1"/><path d="M3.7 10H14v1H3.7z" class="st0"/><circle cx="2.6" cy="10.5" r=".6" class="st1"/><path d="M3.7 13H14v1H3.7z" class="st0"/><circle cx="2.6" cy="13.5" r=".6" class="st1"/></svg>`

And you could remove the `class` attributes to make it even smaller!

**Comment by madamadami** [comment]
Thank you very much, now I got it!
