### ISSUE TITLE
Going the other direction

### ISSUE THREAD

**Issue by alexgleason** [tigt/mini-svg-data-uri#21]
Hi, I want to use this package to inline svgs with Webpack asset modules.

When I render them, though, I want to take the data URI and convert it back to plain SVG data so I can dangerouslySetInnerHTML. This way I can control things like the fill color with CSS.

Any suggestions on how to achieve that?

**Comment by alexgleason** [comment]
Nvm, [`react-inlinesvg`](https://github.com/gilbarbara/react-inlinesvg) does this for me:

```js
<InlineSVG src={src} />
```

src can be literally anything, including a remote URL or a data URI. Very nice. Thanks for this nice script.

**Comment by tigt** [comment]
Nice to see you found a solution. If you or anyone else viewing this issue are curious how to do it vanilla, I’m pretty sure reversing the output is doable through `decodeURIComponent()`.
