### ISSUE TITLE
CLI usage example in README.md incorrect (typo?)

### ISSUE THREAD

**Issue by arminbw** [tigt/mini-svg-data-uri#23]
On my first try after installment I got a `command not found` error. I think there is a typo in the Readme file.

[https://github.com/tigt/mini-svg-data-uri#cli](https://github.com/tigt/mini-svg-data-uri#cli)
If I am not mistaken it should state `mini-svg-data-uri` here, not `mini-svg-to-data-uri`.

**Comment by tigt** [comment]
Ah, yep, good catch. The `--help` flag even says as much.

**Comment by tigt** [comment]
Fixed by 00dc78c8f77eb7b47299a9e3d564749105810c9c, published to NPM as v1.4.4
