### ISSUE TITLE
Feature request: files -> SASS variables

### ISSUE THREAD

**Issue by Hlsgs** [tigt/mini-svg-data-uri#6]
Can this be made to take a list of files in Grunt and output SASS variables in an SCSS file?
It would be a great companion to [grunt-base64](https://github.com/BrightcoveOS/grunt-base64)

Thank you!

**Comment by tigt** [comment]
That would probably be a job for a separate, hypothetical `grunt-mini-svg-data-uri` package. I've never used Grunt, so I unfortunately wouldn't do a good job making it.
